# Generated by Django 3.1.2 on 2021-01-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angulo',
            name='date',
            field=models.DateField(default='2021-01-13'),
        ),
    ]
